# Generated by Django 3.0.1 on 2019-12-19 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20191219_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Type'),
        ),
    ]
