# Generated by Django 3.0.1 on 2019-12-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20191219_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='friends',
            field=models.ManyToManyField(related_name='_member_friends_+', to='backend.Member'),
        ),
    ]
