# Generated by Django 3.0.1 on 2019-12-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_member_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='_member_friends_+', to='backend.Member'),
        ),
    ]
