# Generated by Django 3.0.2 on 2020-01-05 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20200105_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField(choices=[('r', '#d4002d'), ('g', '#76b82a'), ('t', '#00afcb'), ('y', '#f7a600'), ('o', '#ec6608'), ('v', '#af1280'), ('b', '#005ca9')])),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Type')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='profile_picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ProfilePicture'),
        ),
    ]
