# Generated by Django 3.0.2 on 2020-01-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20200105_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='priority',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
