# Generated by Django 3.0.2 on 2020-01-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_habit_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_member_friends_+', to='backend.Member'),
        ),
    ]
